FROM php:7.4-apache
RUN docker-php-ext-install mysqli
# Below is the way we can use without docker-compose file it can be obtained from docker hub
# FROM php:7.4-cli
# COPY . /usr/src/myapp
# WORKDIR /usr/src/myapp
# CMD [ "php", "./index.php" ]